### ISSUE TITLE
BadRequestError: Request disconnected during file upload stream parsing

### ISSUE THREAD

**Issue by sorokinvj** [jaydenseric/apollo-upload-client#149]
hey guys, please help me with this issue, I was trying to implement upload-client with so many different ways, but all the time I cannot handle (I think) it properly. 

In most cases createWriteStream produce a zero byte file. 
If I attach on('error) to stream it gets an error: 

```
(node:13672) UnhandledPromiseRejectionWarning: BadRequestError: Request disconnected during file upload stream parsing.
[server]     at IncomingMessage.request.once (/Users/vladislavsorokin/webprojects/logi-apollo/node_modules/graphql-upload/lib/processRequest.js:245:35)
[server]     at Object.onceWrapper (events.js:273:13)
[server]     at IncomingMessage.emit (events.js:182:13)
[server]     at resOnFinish (_http_server.js:564:7)
[server]     at ServerResponse.emit (events.js:187:15)
[server]     at onFinish (_http_outgoing.js:671:10)
[server]     at process.internalTickCallback (internal/process/next_tick.js:70:11)
[server] (node:13672) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[server] (node:13672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm able to see incoming file in resolver, but confused how to use createReadStream correctly
I tried all the examples I found (jaydenseric, Ben Awad on youtube), but it all failed. Certainly, I'm doing something wrong. Please, help!

Link handling:

```
const link = createUploadLink({ uri: 'http://localhost:4000/graphql' })

const authLink = setContext((_, { headers }) => {
  // get the authentication token from local storage if it exists
  const token = localStorage.getItem('token');
  // return the headers to the context so httpLink can read them
  return {
    headers: {
      ...headers,
      authorization: token,
    }
  }
})

const errorlink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
      ),
    );

  if (networkError) console.log(`[Network error]: ${networkError}`)
})


const alink = ApolloLink.from([
  authLink,
  errorlink,
  link
])


const client = new ApolloClient({
  link: alink,
  cache: new InMemoryCache(),
})
```

resolvers.js:

```

const storeUpload = async (file) => {
    const { createReadStream, filename, mimetype } = await file
    const stream = createReadStream()
    new Promise((resolve, reject) => 
            stream
            .on('error', error => {
                if (stream.truncated)
                  // Delete the truncated file.
                  fs.unlinkSync(path)
                reject(error)
              })
              .pipe(fs.createWriteStream(filename))
              .on('error', error => reject(error))
              .on('finish', () => resolve())
            )
    return file
}

exports.resolvers = {

    Mutation: {

        singleUpload: (root, { file }) => storeUpload(file),

    }
}
```
schema.js

```
const { gql } = require('apollo-server-express');

exports.typeDefs = gql`

    type File {
        filename: String!
        mimetype: String!
    }

    type Mutation {

        singleUpload(
            file: Upload!
        ): File!
    }
`
```

React component:

```
import React from 'react'

import gql from 'graphql-tag'
import { Mutation } from 'react-apollo'
export const UPLOAD_FILE = gql`
  mutation uploadFile($file: Upload!) {
    singleUpload(file: $file) {
      filename
    }
  }
`;

const FileUpload = () => {
  return (   
    <Mutation mutation={UPLOAD_FILE}>
      {uploadFile => (
        <input
        type="file"
        required
        onChange={({ target: { validity, files: [file] } }) => {
          validity.valid && uploadFile({ variables: { file } })
        }}
       />
      )}
    </Mutation>
  );
};

export default FileUpload
```

**Comment by tufail** [comment]
Hi @sorokinvj , Is this works for you , I am also facing same issue . Can you please update the code , what exactly the fix. sorry , I didn't get

is this line you have added.
```
singleUpload: **async**(root, { file }) => **await** storeUpload(file),      // not sure how it worked for you
```
