### ISSUE TITLE
How to use this with graphql-codegen?

### ISSUE THREAD

**Issue by joshbedo** [jaydenseric/apollo-upload-client#243]
Trying to get these two to play together nicely but not having any luck. When i generate my graphql file with codegen it can't find the Upload scalar. I tried adding it into the config but no cigar. Anyone know how to tie these two together? I need to get image upload working soon.

```
Found 1 error

  ✖ src/gql/generated/graphql.tsx
    AggregateError:
        GraphQLDocumentError: Variable "$file" cannot be non-input type "Upload".
            at /Users/joshbedo/Desktop/projects/influencial-1.0/client/src/gql/gql.graphql:83:28
        GraphQLDocumentError: Unknown argument "file" on field "Mutation.uploadFile".
            at /Users/joshbedo/Desktop/projects/influencial-1.0/client/src/gql/gql.graphql:84:14
        at new AggregateError (/Users/joshbedo/Desktop/projects/influencial-1.0/client/node_modules/@ardatan/aggregate-error/index.cjs.js:141:24)
        at Object.checkValidationErrors (/Users/joshbedo/Desktop/projects/influencial-1.0/client/node_modules/@graphql-tools/utils/index.cjs.js:517:15)
        at Object.codegen (/Users/joshbedo/Desktop/projects/influencial-1.0/client/node_modules/@graphql-codegen/core/index.cjs.js:99:15)
        at async process (/Users/joshbedo/Desktop/projects/influencial-1.0/client/node_modules/@graphql-codegen/cli/bin.js:845:56)
        at async Promise.all (index 0)
        at async /Users/joshbedo/Desktop/projects/influencial-1.0/client/node_modules/@graphql-codegen/cli/bin.js:852:37
        at async Task.task (/Users/joshbedo/Desktop/projects/influencial-1.0/client/node_modules/@graphql-codegen/cli/bin.js:634:17)
    AggregateError:
        GraphQLDocumentError: Variable "$file" cannot be non-input type "Upload".
```

**Comment by jaydenseric** [comment]
This is more of a `graphql-codegen` usage question; that project is a better place to ask for help. I'm not very familiar with `graphql-codegen`, but maybe you need to teach it about the scalars used in your project? In this instance the `Upload` scalar.

**Comment by joshbedo** [comment]
Alright no problem, I'll use that project to ask the question. Yeah it's odd that's what I thought too but adding the scalar to the schema just seemed to introduce no problems around .getFields not existing.
