### ISSUE TITLE
warning at compilation

### ISSUE THREAD

**Issue by vladoro** [jaydenseric/apollo-upload-client#76]
compilation with webpack gives some warnings

    WARNING in ./node_modules/apollo-upload-client/lib/index.mjs
    5:17-34 "export 'default' (imported as 'apolloLinkDefault') was not found in 'apollo-link'
        at HarmonyImportSpecifierDependency._getErrors (/dev/project/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
        at HarmonyImportSpecifierDependency.getWarnings (/dev/project/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
        at Compilation.reportDependencyErrorsAndWarnings (/dev/project/node_modules/webpack/lib/Compilation.js:703:24)
        at Compilation.finish (/dev/project/node_modules/webpack/lib/Compilation.js:561:9)
        at applyPluginsParallel.err (/dev/project/node_modules/webpack/lib/Compiler.js:502:17)
        at /dev/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
        at _addModuleChain (/dev/project/node_modules/webpack/lib/Compilation.js:507:11)
        at processModuleDependencies.err (/dev/project/node_modules/webpack/lib/Compilation.js:477:14)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
    
    WARNING in ./node_modules/apollo-upload-client/lib/index.mjs
    7:2-29 "export 'default' (imported as 'apolloLinkHttpCommonDefault') was not found in 'apollo-link-http-common'
        at HarmonyImportSpecifierDependency._getErrors (/dev/project/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:65:15)
        at HarmonyImportSpecifierDependency.getWarnings (/dev/project/node_modules/webpack/lib/dependencies/HarmonyImportSpecifierDependency.js:39:15)
        at Compilation.reportDependencyErrorsAndWarnings (/dev/project/node_modules/webpack/lib/Compilation.js:703:24)
        at Compilation.finish (/dev/project/node_modules/webpack/lib/Compilation.js:561:9)
        at applyPluginsParallel.err (/dev/project/node_modules/webpack/lib/Compiler.js:502:17)
        at /dev/project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
        at _addModuleChain (/dev/project/node_modules/webpack/lib/Compilation.js:507:11)
        at processModuleDependencies.err (/dev/project/node_modules/webpack/lib/Compilation.js:477:14)
        at _combinedTickCallback (internal/process/next_tick.js:131:7)
        at process._tickDomainCallback (internal/process/next_tick.js:218:9)
`
{
    "apollo-upload-client": {
      "version": "7.1.0",
      "resolved": "https://registry.npmjs.org/apollo-upload-client/-/apollo-upload-client-7.1.0.tgz",
      "integrity": "sha512-QITVOY2Rzz1lWxCgPSaYJdhKxgR3N/roC4D6oCWywHV6cRjoYZhlwoIAmRAWryP4cK1GevM0ULcHk3x16TEjVw==",
      "requires": {
        "@babel/runtime": "7.0.0-beta.40",
        "apollo-link-http-common": "0.2.3",
        "extract-files": "3.1.0"
      },
      "dependencies": {
        "@babel/runtime": {
          "version": "7.0.0-beta.40",
          "resolved": "https://registry.npmjs.org/@babel/runtime/-/runtime-7.0.0-beta.40.tgz",
          "integrity": "sha512-vIM68NUCWauZJTFoVUG1lggva1I8FLB9zFKwWG7Xjin4FkHpEKJv2y4x1DGVPVt93S5/zHSBj1bXYEuxOkFGzg==",
          "requires": {
            "core-js": "2.5.3",
            "regenerator-runtime": "0.11.1"
          }
        }
      }
    },
    "apollo-link": {
      "version": "1.2.1",
      "resolved": "https://registry.npmjs.org/apollo-link/-/apollo-link-1.2.1.tgz",
      "integrity": "sha512-6Ghf+j3cQLCIvjXd2dJrLw+16HZbWbwmB1qlTc41BviB2hv+rK1nJr17Y9dWK0UD4p3i9Hfddx3tthpMKrueHg==",
      "requires": {
        "@types/node": "9.4.6",
        "apollo-utilities": "1.0.6",
        "zen-observable-ts": "0.8.8"
      },
      "dependencies": {
        "@types/node": {
          "version": "9.4.6",
          "resolved": "https://registry.npmjs.org/@types/node/-/node-9.4.6.tgz",
          "integrity": "sha512-CTUtLb6WqCCgp6P59QintjHWqzf4VL1uPA27bipLAPxFqrtK1gEYllePzTICGqQ8rYsCbpnsNypXjjDzGAAjEQ=="
        }
      }
    },
    "apollo-link-http-common": {
      "version": "0.2.3",
      "resolved": "https://registry.npmjs.org/apollo-link-http-common/-/apollo-link-http-common-0.2.3.tgz",
      "integrity": "sha512-gZ5xp2ZlX9Ie0HR/bVDxD4073UAMdZC/QhPQifh/AV6YCOTuj3ZkaAf89KnuQCifWVXO3yXD/53SWm7VrsjCdQ==",
      "requires": {
        "apollo-link": "1.2.1"
      }
    }
}
`

**Comment by jaydenseric** [comment]
This was expected, see https://github.com/jaydenseric/apollo-upload-client/issues/72#issuecomment-371000668 and https://github.com/jaydenseric/apollo-upload-client/issues/74.

If you upgrade to [v8](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v8.0.0) you won't get them anymore.
